// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NokiaHUIServer.Models;

namespace NokiaHUIServer.Migrations
{
    [DbContext(typeof(PacientProfileContext))]
    [Migration("20181020200736_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NokiaHUIServer.Models.MedCard", b =>
                {
                    b.Property<int>("MedCardId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AB0");

                    b.Property<int>("Grow");

                    b.Property<string>("MedHistory");

                    b.Property<int>("PacientProfileId");

                    b.Property<string>("Rh");

                    b.Property<int>("Weight");

                    b.HasKey("MedCardId");

                    b.ToTable("MedCard");
                });

            modelBuilder.Entity("NokiaHUIServer.Models.PacientProfile", b =>
                {
                    b.Property<int>("PacientProfileId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalPhoneNumber");

                    b.Property<string>("Address");

                    b.Property<string>("BirthDay");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("MedCardId");

                    b.Property<int?>("MedCardId1");

                    b.Property<string>("Passw");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("PacientProfileId");

                    b.HasIndex("MedCardId1");

                    b.ToTable("PacientProfiles");
                });

            modelBuilder.Entity("NokiaHUIServer.Models.PacientProfile", b =>
                {
                    b.HasOne("NokiaHUIServer.Models.MedCard", "MedCard")
                        .WithMany()
                        .HasForeignKey("MedCardId1");
                });
#pragma warning restore 612, 618
        }
    }
}
